version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true # here will override the DEV variable in Dockerfile. Now it will set to true in Dockerfile.
    ports: 
      - "8000:8000"
    volumes: 
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"